version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - run:
          name: Install Maven
          command: sudo apt-get install -y maven
      - run:
          name: Build and Test
          command: mvn clean test

workflows:
  version: 2
  build:
    jobs:
      - build
