version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11  # Obraz z OpenJDK 11
    steps:
      - checkout  # Pobranie kodu źródłowego z repozytorium

      # Kompilacja kodu aplikacji i testów
      - run:
          name: Compile Application and Tests
          command: |
            mkdir -p bin/main bin/test
            # Kompilacja kodu aplikacji
            javac -d bin/main -cp lib/junit-platform-console-standalone-1.9.3.jar src/main/java/*.java
            # Kompilacja testów
            javac -d bin/test -cp "lib/junit-platform-console-standalone-1.9.3.jar:bin/main" src/test/java/*.java

      # Uruchamianie testów jednostkowych
      - run:
          name: Run Unit Tests
          command: |
            java -jar lib/junit-platform-console-standalone-1.9.3.jar \
              --class-path "bin/main:bin/test" \
              --scan-class-path

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
